#version 460
layout(binding = 0) uniform sampler2D img_cfa;
layout(binding = 1, r8) uniform writeonly image2D img_vh;
layout(binding = 2, r8) uniform writeonly image2D img_pq;
layout(binding = 3, r32f) uniform writeonly image2D img_lp;

layout(local_size_x = 16, local_size_y = 16) in;

void main(){
    ivec2 ipos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = textureSize(img_cfa,0);
    if(any(greaterThanEqual(ipos,size))) return;
#define IP(dx,dy) (ipos + ivec2(dx,dy))
#define cfa(dx,dy) texelFetch(img_cfa, IP(dx,dy), 0).r
    vec2 vhs = vec2(0.0);
    for(int i=-1;i<=1;i++){
        vhs += vec2(
            cfa(i,-3) - 3.0*cfa(i,-2) - cfa(i,-1) + 6.0*cfa(i,0) - cfa(i,1) - 3.0*cfa(i,2) + cfa(i,3),
            cfa(-3,i) - 3.0*cfa(-2,i) - cfa(-1,i) + 6.0*cfa(0,i) - cfa(1,i) - 3.0*cfa(2,i) + cfa(3,i)
        );
    }
    vhs*=vhs;
    float vh = vhs.x/(1e-5 + vhs.x + vhs.y);
    imageStore(img_vh, ipos, vec4(vh));
    if(((ipos.x+ipos.y)&1)==0){
        vec2 pqs = vec2(1e-5);
        for(int i=-1;i<=1;i++){
            pqs += vec2(
                cfa(-3+i,-3+i) - cfa(1+i,-1+i) - cfa(1+i,1+i) + cfa(3+i,3+i) - 3.0*(cfa(-2+i,-2+i)+cfa(2+i,2+i)) + 6.0*cfa(i,i),
                cfa(3+i,-3-i) - cfa(1+i,-1-i) - cfa(-1+i,1-i) + cfa(-3+i,3-i) - 3.0*(cfa(2+i,-2-i)+cfa(-2+i,2-i)) + 6.0*cfa(i,-i)
            );
        }
        pqs*=pqs;
        float pq = pqs.x/(pqs.x+pqs.y);
        imageStore(img_pq, ivec2(ipos.x/2, ipos.y), vec4(pq));
    }else{
        float lp=0.0; int off=((ipos.x&1)==1)?-1:1;
        const float w[3]={0.5,1.0,0.5};
        for(int j=-1;j<=1;j++) for(int i=-1;i<=1;i++) lp+=w[j+1]*w[i+1]*cfa(i+off,j);
        imageStore(img_lp, ivec2(ipos.x/2, ipos.y), vec4(max(1e-6, lp)));
    }
#undef cfa
}
